const $=(s,r=document)=>r.querySelector(s);const $$=(s,r=document)=>[...r.querySelectorAll(s)];
const params=new URLSearchParams(location.search);let room=params.get('room')||localStorage.getItem('simo.student.room.v1')||'';let name=localStorage.getItem('simo.student.name.v1')||'';let studentId=localStorage.getItem('simo.student.id.v1')||crypto.randomUUID();localStorage.setItem('simo.student.id.v1',studentId);
let socket=null,reconnectTimer=null,currentQuestion=null,reaction=null,workspace={enabled:false,controllerStudentId:null,strokes:[],note:'',prompt:'',title:'Ortak Çalışma'};let selectedAnswer=null,drawState=null;
function toast(t,ms=2200){const e=$('#toast');e.textContent=t;e.classList.remove('hidden');clearTimeout(e._t);e._t=setTimeout(()=>e.classList.add('hidden'),ms)}
function wsURL(){const p=location.protocol==='https:'?'wss:':'ws:';return `${p}//${location.host}/ws?room=${encodeURIComponent(room)}&role=student&studentId=${encodeURIComponent(studentId)}&name=${encodeURIComponent(name)}`}
function send(d){if(socket?.readyState===WebSocket.OPEN){socket.send(JSON.stringify(d));return true}toast('Bağlantı hazırlanıyor');return false}
function escapeHTML(s=''){return String(s).replace(/[&<>\"]/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','\"':'&quot;'}[c]))}
function setConn(ok){$('#studentConn').textContent=ok?'Canlı':'Bağlanıyor';$('#studentDot').classList.toggle('live',ok)}
function showJoin(){ $('#joinScreen').classList.remove('hidden');$('#studentShell').classList.add('hidden');$('#joinRoom').value=room;$('#joinName').value=name }
function showStudent(){ $('#joinScreen').classList.add('hidden');$('#studentShell').classList.remove('hidden');$('#studentRoomText').textContent=`Oda ${room}`;$('#studentNameText').textContent=name||'Öğrenci' }
function connect(){if(!room||!name)return showJoin();clearTimeout(reconnectTimer);if(socket&&[0,1].includes(socket.readyState))return;showStudent();setConn(false);socket=new WebSocket(wsURL());socket.onopen=()=>setConn(true);socket.onmessage=e=>{try{handle(JSON.parse(e.data))}catch{}};socket.onclose=()=>{setConn(false);reconnectTimer=setTimeout(connect,1800)};socket.onerror=()=>setConn(false)}
function handle(d){if(d.type==='snapshot'){if(d.classTitle)$('#studentTitle').textContent=d.classTitle;currentQuestion=d.currentQuestion||null;workspace=d.workspace||workspace;renderQuestion();renderWorkspace();return}if(d.type==='class_title')$('#studentTitle').textContent=d.title||'Simo Classroom';if(d.type==='question'){currentQuestion=d.question||null;selectedAnswer=null;renderQuestion()}if(d.type==='workspace'){workspace=d.workspace||workspace;renderWorkspace();renderCanvas()}if(d.type==='workspace_stroke'){workspace.strokes=workspace.strokes||[];workspace.strokes.push(d.stroke);renderCanvas()}if(d.type==='workspace_note'){workspace.note=d.note||'';if($('#studentWorkspaceNote').value!==workspace.note)$('#studentWorkspaceNote').value=workspace.note}if(d.type==='selected_student'){} }
function renderQuestion(){const q=currentQuestion;const area=$('#studentAnswerArea'),res=$('#studentResult');res.className='student-result hidden';if(!q){$('#studentQuestion').textContent='Öğretmenin sorusu burada görünecek.';area.innerHTML='<div class="muted small">Soru bekleniyor.</div>';$('#studentStatusText').textContent='Soru bekleniyor';return}$('#studentQuestion').textContent=q.prompt||'Soru';$('#studentStatusText').textContent='Yeni soru';if(['quiz','poll','truefalse'].includes(q.type)){area.innerHTML=(q.options||[]).map((o,i)=>`<button class="student-option" data-answer="${i}">${escapeHTML(o)}</button>`).join('');$$('[data-answer]').forEach(b=>b.onclick=()=>{selectedAnswer=Number(b.dataset.answer);$$('[data-answer]').forEach(x=>x.classList.toggle('selected',x===b));send({type:'answer',value:selectedAnswer});$('#studentStatusText').textContent='Cevap gönderildi';if(q.reveal&&q.correctIndex!=null)showResult(selectedAnswer===q.correctIndex)})}else{area.innerHTML=`<div class="field"><textarea id="textAnswer" placeholder="Cevabını yaz..."></textarea></div><button class="btn primary" id="sendTextAnswer" style="width:100%;margin-top:8px">Cevabı Gönder</button>`;$('#sendTextAnswer').onclick=()=>{const v=$('#textAnswer').value.trim();if(!v)return toast('Cevabını yaz');send({type:'answer',value:v});$('#studentStatusText').textContent='Cevap gönderildi';toast('Cevabın gönderildi')}}}
function showResult(ok){const r=$('#studentResult');r.className=`student-result ${ok?'good':'bad'}`;r.textContent=ok?'✓ Doğru cevap':'• Cevabın gönderildi'}
function renderReactions(){$$('[data-reaction]').forEach(b=>b.classList.toggle('active',b.dataset.reaction===reaction))}
function renderWorkspace(){const box=$('#studentWorkspace');box.classList.toggle('hidden',!workspace.enabled);if(!workspace.enabled)return;$('#studentWorkspaceTitle').textContent=workspace.title||'Ortak Çalışma';$('#studentWorkspacePrompt').textContent=workspace.prompt||'Birlikte çözün.';const control=workspace.controllerStudentId===studentId;$('#studentControlBadge').textContent=control?'Kontrol sende':'İzle';$('#studentControlBadge').className=control?'badge good':'badge';$('#controlBanner').classList.toggle('hidden',!control);$('#studentCanvas').style.pointerEvents=control?'auto':'none';$('#studentWorkspaceNote').readOnly=!control;if($('#studentWorkspaceNote').value!==String(workspace.note||''))$('#studentWorkspaceNote').value=workspace.note||'';renderCanvas()}
function setupCanvas(){const c=$('#studentCanvas');function point(e){const r=c.getBoundingClientRect();return[(e.clientX-r.left)/r.width*c.width,(e.clientY-r.top)/r.height*c.height]}c.onpointerdown=e=>{if(workspace.controllerStudentId!==studentId)return;drawState={id:crypto.randomUUID(),color:'#0f766e',width:4,points:[point(e)]};c.setPointerCapture?.(e.pointerId)};c.onpointermove=e=>{if(!drawState)return;drawState.points.push(point(e));renderCanvas([...(workspace.strokes||[]),drawState])};c.onpointerup=()=>{if(!drawState)return;const s=drawState;drawState=null;workspace.strokes=[...(workspace.strokes||[]),s];renderCanvas();send({type:'workspace_stroke',stroke:s})};$('#studentWorkspaceNote').oninput=e=>{if(workspace.controllerStudentId===studentId)send({type:'workspace_note',note:e.target.value})}}
function renderCanvas(override=null){const c=$('#studentCanvas');if(!c)return;const x=c.getContext('2d');x.clearRect(0,0,c.width,c.height);x.fillStyle='#fff';x.fillRect(0,0,c.width,c.height);x.strokeStyle='#eef2f7';x.lineWidth=1;for(let i=40;i<c.width;i+=40){x.beginPath();x.moveTo(i,0);x.lineTo(i,c.height);x.stroke()}for(let i=40;i<c.height;i+=40){x.beginPath();x.moveTo(0,i);x.lineTo(c.width,i);x.stroke()}for(const s of (override||workspace.strokes||[])){if(!s.points?.length)continue;x.beginPath();x.strokeStyle=s.color||'#0f766e';x.lineWidth=s.width||4;x.lineCap='round';x.lineJoin='round';x.moveTo(s.points[0][0],s.points[0][1]);for(const p of s.points.slice(1))x.lineTo(p[0],p[1]);x.stroke()}}
$('#joinBtn').onclick=()=>{room=$('#joinRoom').value.trim();name=$('#joinName').value.trim();if(!room||!name)return toast('Oda kodu ve adını yaz');localStorage.setItem('simo.student.room.v1',room);localStorage.setItem('simo.student.name.v1',name);history.replaceState(null,'',`/student.html?room=${encodeURIComponent(room)}`);connect()};$$('[data-reaction]').forEach(b=>b.onclick=()=>{reaction=reaction===b.dataset.reaction?null:b.dataset.reaction;renderReactions();send({type:'reaction',reaction})});setupCanvas();if(room&&name)connect();else showJoin();renderReactions();
